# -*- coding: utf-8 -*-
"""Copy of Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cs2OXnWIkmgsY9anL_OPQOnkXgTi9gdS
"""

import pandas as pd

# Step 1 - Load the file
df = pd.read_csv('/content/GTADATA.csv', encoding='latin-1')
print("Rows loaded:", len(df))

# Step 2 - Save as clean UTF-8
df.to_csv('/content/GTADATA_CLEAN.csv', index=False, encoding='utf-8-sig')
print("Clean file saved successfully")

from google.colab import files
files.download('/content/GTADATA_CLEAN.csv')

pip install mysql-connector-python

from google.colab import files
uploaded = files.upload()

from google.colab import files
files.download('/content/GTADATA_FINAL.csv')

import pandas as pd
from google.colab import files

# Load uploaded file
df = pd.read_csv('/content/GTADATA.csv', encoding='latin-1', low_memory=False)
print("Loaded. Rows:", len(df))

# Fix booleans - fill empty cells with False first
df['voted_up'] = df['voted_up'].fillna(False).astype(bool).astype(int)
df['steam_purchase'] = df['steam_purchase'].fillna(False).astype(bool).astype(int)
df['recieved_for_free'] = df['recieved_for_free'].fillna(False).astype(bool).astype(int)
df['written_during_early_access'] = df['written_during_early_access'].fillna(False).astype(bool).astype(int)

# Clean review text
df['review'] = df['review'].fillna('').astype(str).str.replace('"', '', regex=False)
df['review'] = df['review'].str.replace('\n', ' ', regex=False)
df['review'] = df['review'].str.replace('\r', ' ', regex=False)

# Save
df.to_csv('/content/GTADATA_FINAL.csv', index=False, encoding='utf-8', quoting=1)
print("Saved. Rows:", len(df))

# Download immediately
files.download('/content/GTADATA_FINAL.csv')

with open('/content/GTADATA_FINAL.csv', 'r', encoding='utf-8') as f:
    for i, line in enumerate(f):
        print(repr(line))
        if i == 2:
            break

import pandas as pd
from google.colab import files

# Load and fix everything
df = pd.read_csv('/content/GTADATA.csv', encoding='latin-1', low_memory=False)

# Keep only the 16 columns we need
df = df[['id','language','review','created','voted_up','votes_up',
         'comment_count','steam_purchase','recieved_for_free',
         'written_during_early_access','author_num_games_owned',
         'author_num_reviews','author_playtime_forever',
         'author_playtime_last_two_weeks','author_playtime_at_review',
         'author_last_played']]

# Fix booleans
df['voted_up'] = df['voted_up'].fillna(False).astype(bool).astype(int)
df['steam_purchase'] = df['steam_purchase'].fillna(False).astype(bool).astype(int)
df['recieved_for_free'] = df['recieved_for_free'].fillna(False).astype(bool).astype(int)
df['written_during_early_access'] = df['written_during_early_access'].fillna(False).astype(bool).astype(int)

# Fix review text
df['review'] = df['review'].fillna('').astype(str).str.replace('"', '', regex=False)
df['review'] = df['review'].str.replace('\n', ' ', regex=False)
df['review'] = df['review'].str.replace('\r', ' ', regex=False)

# Fix votes_up to integer
df['votes_up'] = df['votes_up'].fillna(0).astype(int)

print("Rows:", len(df))
print("Columns:", df.columns.tolist())
print(df.head(2))

# Save without BOM, without index
df.to_csv('/content/GTADATA_FINAL.csv', index=False, encoding='utf-8', quoting=1)
print("Saved successfully")

files.download('/content/GTADATA_FINAL.csv')

import pandas as pd
df = pd.read_csv('/content/GTADATA.csv', encoding='latin-1', low_memory=False)
print(df.columns.tolist())

import pandas as pd
from google.colab import files

# Load and fix BOM on first column
df = pd.read_csv('/content/GTADATA.csv', encoding='utf-8-sig', low_memory=False)

# Rename BOM column just in case
df.columns = df.columns.str.replace('ï»¿', '', regex=False).str.strip()

# Keep only our 16 columns
df = df[['id','language','review','created','voted_up','votes_up',
         'comment_count','steam_purchase','recieved_for_free',
         'written_during_early_access','author_num_games_owned',
         'author_num_reviews','author_playtime_forever',
         'author_playtime_last_two_weeks','author_playtime_at_review',
         'author_last_played']]

# Fix booleans
df['voted_up'] = df['voted_up'].fillna(False).astype(bool).astype(int)
df['steam_purchase'] = df['steam_purchase'].fillna(False).astype(bool).astype(int)
df['recieved_for_free'] = df['recieved_for_free'].fillna(False).astype(bool).astype(int)
df['written_during_early_access'] = df['written_during_early_access'].fillna(False).astype(bool).astype(int)

# Fix review text
df['review'] = df['review'].fillna('').astype(str).str.replace('"', '', regex=False)
df['review'] = df['review'].str.replace('\n', ' ', regex=False)
df['review'] = df['review'].str.replace('\r', ' ', regex=False)

# Fix votes_up to integer
df['votes_up'] = df['votes_up'].fillna(0).astype(int)

print("Rows:", len(df))
print("Columns:", df.columns.tolist())

# Save
df.to_csv('/content/GTADATA_FINAL.csv', index=False, encoding='utf-8')
print("Saved successfully")

files.download('/content/GTADATA_FINAL.csv')

import pandas as pd
from google.colab import files

df = pd.read_csv('/content/GTADATA.csv', encoding='utf-8-sig', low_memory=False)
df.columns = df.columns.str.replace('ï»¿', '', regex=False).str.strip()
df = df[['id','language','review','created','voted_up','votes_up',
         'comment_count','steam_purchase','recieved_for_free',
         'written_during_early_access','author_num_games_owned',
         'author_num_reviews','author_playtime_forever',
         'author_playtime_last_two_weeks','author_playtime_at_review',
         'author_last_played']]

df['review'] = df['review'].fillna('').astype(str).str.replace('\n',' ').str.replace('\r',' ').str.replace('|','')

df.to_csv('/content/GTADATA_FINAL.csv', index=False, encoding='utf-8', sep='|')
print("Done:", len(df), "rows")
files.download('/content/GTADATA_FINAL.csv')

import pandas as pd
from google.colab import files

df = pd.read_csv('/content/GTADATA.csv', encoding='utf-8-sig', low_memory=False)
df.columns = df.columns.str.replace('ï»¿', '', regex=False).str.strip()
df = df[['id','language','review','created','voted_up','votes_up',
         'comment_count','steam_purchase','recieved_for_free',
         'written_during_early_access','author_num_games_owned',
         'author_num_reviews','author_playtime_forever',
         'author_playtime_last_two_weeks','author_playtime_at_review',
         'author_last_played']]

# Fix booleans to 1/0
df['voted_up'] = df['voted_up'].map({'True': 1, 'False': 0, True: 1, False: 0}).fillna(0).astype(int)
df['steam_purchase'] = df['steam_purchase'].map({'True': 1, 'False': 0, True: 1, False: 0}).fillna(0).astype(int)
df['recieved_for_free'] = df['recieved_for_free'].map({'True': 1, 'False': 0, True: 1, False: 0}).fillna(0).astype(int)
df['written_during_early_access'] = df['written_during_early_access'].map({'True': 1, 'False': 0, True: 1, False: 0}).fillna(0).astype(int)

# Fix votes_up
df['votes_up'] = df['votes_up'].fillna(0).astype(int)

# Fix review text
df['review'] = df['review'].fillna('').astype(str).str.replace('\n',' ').str.replace('\r',' ').str.replace('|','')

df.to_csv('/content/GTADATA_FINAL.csv', index=False, encoding='utf-8', sep='|')
print("Done:", len(df), "rows")
print(df[['voted_up','steam_purchase']].head(3))
files.download('/content/GTADATA_FINAL.csv')

import pandas as pd

df = pd.read_csv('/content/GTADATA.csv', encoding='utf-8-sig', low_memory=False)
df.columns = df.columns.str.replace('ï»¿', '', regex=False).str.strip()
df = df[['id','language','review','created','voted_up','votes_up',
         'comment_count','steam_purchase','recieved_for_free',
         'written_during_early_access','author_num_games_owned',
         'author_num_reviews','author_playtime_forever',
         'author_playtime_last_two_weeks','author_playtime_at_review',
         'author_last_played']]

print(repr(df['review'].iloc[599]))
print("---")
print(df.iloc[599])

import pandas as pd
from google.colab import files

df = pd.read_csv('/content/GTADATA.csv', encoding='utf-8-sig', low_memory=False)
df.columns = df.columns.str.replace('ï»¿', '', regex=False).str.strip()
df = df[['id','language','review','created','voted_up','votes_up',
         'comment_count','steam_purchase','recieved_for_free',
         'written_during_early_access','author_num_games_owned',
         'author_num_reviews','author_playtime_forever',
         'author_playtime_last_two_weeks','author_playtime_at_review',
         'author_last_played']]

df['voted_up'] = df['voted_up'].map({'True': 1, 'False': 0, True: 1, False: 0}).fillna(0).astype(int)
df['steam_purchase'] = df['steam_purchase'].map({'True': 1, 'False': 0, True: 1, False: 0}).fillna(0).astype(int)
df['recieved_for_free'] = df['recieved_for_free'].map({'True': 1, 'False': 0, True: 1, False: 0}).fillna(0).astype(int)
df['written_during_early_access'] = df['written_during_early_access'].map({'True': 1, 'False': 0, True: 1, False: 0}).fillna(0).astype(int)
df['votes_up'] = df['votes_up'].fillna(0).astype(int)

# Remove ALL problematic characters from review
df['review'] = df['review'].fillna('').astype(str)
df['review'] = df['review'].str.replace('\\', '', regex=False)
df['review'] = df['review'].str.replace('|', '', regex=False)
df['review'] = df['review'].str.replace('\n', ' ', regex=False)
df['review'] = df['review'].str.replace('\r', ' ', regex=False)

df.to_csv('/content/GTADATA_FINAL.csv', index=False, encoding='utf-8', sep='|')
print("Done:", len(df), "rows")
files.download('/content/GTADATA_FINAL.csv')

import pandas as pd

df = pd.read_csv('/content/GTADATA.csv', encoding='utf-8-sig', low_memory=False)
df.columns = df.columns.str.replace('ï»¿', '', regex=False).str.strip()

print("Sample created dates:")
print(df['created'].head(10).tolist())
print()
print("Unique date formats found:")
print(df['created'].dtype)
print()
print("Min date:", df['created'].min())
print("Max date:", df['created'].max())

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('/content/GTADATA.csv', encoding='latin-1', low_memory=False)

print("Sample created dates:")
print(df['created'].head(10).tolist())
print()
print("Min date:", df['created'].min())
print("Max date:", df['created'].max())

import pandas as pd

df = pd.read_csv('/content/GTADATA.csv', sep='|', encoding='utf-8', low_memory=False)

print("Sample created dates:")
print(df['created'].head(10).tolist())
print()
print("Min date:", df['created'].min())
print("Max date:", df['created'].max())

# Install VADER sentiment analyzer
!pip install vaderSentiment --quiet

# Import everything
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from collections import Counter
import warnings
warnings.filterwarnings('ignore')

# Download NLTK data
nltk.download('stopwords', quiet=True)
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)

print("All libraries loaded successfully")

# Load the data
df = pd.read_csv('/content/GTADATA.csv', sep='|', encoding='utf-8', low_memory=False)

# Quick confirmation
print("Rows:", len(df))
print("Columns:", df.columns.tolist())
print()
print("First 2 rows:")
print(df[['id', 'language', 'voted_up', 'author_playtime_forever', 'review']].head(2))

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('/content/GTADATA.csv', sep='|', encoding='utf-8', low_memory=False)

print("Rows:", len(df))
print("Columns:", df.columns.tolist())
print()
print(df[['id', 'voted_up', 'author_playtime_forever', 'review']].head(2))

# Convert created to datetime
df['created'] = pd.to_datetime(df['created'], dayfirst=True)

# Convert playtime from minutes to hours
df['playtime_forever_hrs'] = round(df['author_playtime_forever'] / 60, 1)
df['playtime_at_review_hrs'] = round(df['author_playtime_at_review'] / 60, 1)
df['playtime_last_2weeks_hrs'] = round(df['author_playtime_last_two_weeks'] / 60, 1)

# Convert last played to datetime
df['author_last_played'] = pd.to_datetime(df['author_last_played'], dayfirst=True)

# Confirm
print("Date range:", df['created'].min(), "to", df['created'].max())
print("Max playtime (hrs):", df['playtime_forever_hrs'].max())
print("Average playtime (hrs):", round(df['playtime_forever_hrs'].mean(), 1))
print("Data types:")
print(df[['created', 'voted_up', 'playtime_forever_hrs']].dtypes)

!pip install vaderSentiment --quiet
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from collections import Counter
import warnings
warnings.filterwarnings('ignore')
nltk.download('stopwords', quiet=True)
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)
print("Libraries loaded")

df = pd.read_csv('/content/GTADATA.csv', sep='|', encoding='utf-8', low_memory=False)
print("Rows loaded:", len(df))

# Upload file first
from google.colab import files
uploaded = files.upload()

# Install and import
!pip install vaderSentiment --quiet
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from collections import Counter
import warnings
warnings.filterwarnings('ignore')
nltk.download('stopwords', quiet=True)
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)
print("Libraries loaded")

# Load data
df = pd.read_csv('/content/GTADATA.csv', sep='|', encoding='utf-8', low_memory=False)
print("Rows loaded:", len(df))

# Clean and prepare
df['created'] = pd.to_datetime(df['created'], dayfirst=True)
df['author_last_played'] = pd.to_datetime(df['author_last_played'], dayfirst=True)
df['playtime_forever_hrs'] = round(df['author_playtime_forever'] / 60, 1)
df['playtime_at_review_hrs'] = round(df['author_playtime_at_review'] / 60, 1)
df['playtime_last_2weeks_hrs'] = round(df['author_playtime_last_two_weeks'] / 60, 1)

print("Date range:", df['created'].min(), "to", df['created'].max())
print("Max playtime hrs:", df['playtime_forever_hrs'].max())
print("Average playtime hrs:", round(df['playtime_forever_hrs'].mean(), 1))
print("All steps complete")

# Initialise VADER
analyzer = SentimentIntensityAnalyzer()

# Score every review
def get_sentiment_score(text):
    if pd.isna(text) or text == '':
        return 0
    return analyzer.polarity_scores(str(text))['compound']

df['sentiment_score'] = df['review'].apply(get_sentiment_score)

# Quick summary
print("Sentiment scoring complete")
print("Average sentiment score:", round(df['sentiment_score'].mean(), 3))
print("Most negative score:", df['sentiment_score'].min())
print("Most positive score:", df['sentiment_score'].max())
print()
print("Score breakdown:")
print("Positive (>0.05):", len(df[df['sentiment_score'] > 0.05]))
print("Neutral (-0.05 to 0.05):", len(df[(df['sentiment_score'] >= -0.05) & (df['sentiment_score'] <= 0.05)]))
print("Negative (<-0.05):", len(df[df['sentiment_score'] < -0.05]))

plt.figure(figsize=(12, 5))
plt.hist(df['sentiment_score'], bins=50, color='steelblue', edgecolor='white', alpha=0.8)
plt.axvline(x=0, color='red', linestyle='--', linewidth=1.5, label='Neutral line')
plt.axvline(x=df['sentiment_score'].mean(), color='orange', linestyle='--', linewidth=1.5, label=f'Mean: {round(df["sentiment_score"].mean(), 2)}')
plt.title('GTA Online — Sentiment Score Distribution (52,099 Reviews)', fontsize=14, fontweight='bold')
plt.xlabel('Sentiment Score (-1 = Most Negative, +1 = Most Positive)')
plt.ylabel('Number of Reviews')
plt.legend()
plt.tight_layout()
plt.savefig('/content/chart1_sentiment_distribution.png', dpi=150)
plt.show()
print("Chart saved")

# Create player tiers
def assign_tier(hrs):
    if hrs < 10:
        return '1. Casual\n(0-10hrs)'
    elif hrs < 50:
        return '2. Moderate\n(10-50hrs)'
    elif hrs < 200:
        return '3. Dedicated\n(50-200hrs)'
    else:
        return '4. Hardcore\n(200hrs+)'

df['player_tier'] = df['playtime_forever_hrs'].apply(assign_tier)

tier_sentiment = df.groupby('player_tier')['sentiment_score'].mean().reset_index()

plt.figure(figsize=(10, 6))
bars = plt.bar(tier_sentiment['player_tier'],
               tier_sentiment['sentiment_score'],
               color=['#d73027','#fc8d59','#4575b4','#d73027'],
               edgecolor='white', width=0.5)

plt.axhline(y=df['sentiment_score'].mean(), color='black',
            linestyle='--', linewidth=1.5, label=f'Overall Mean: {round(df["sentiment_score"].mean(), 3)}')

for bar, val in zip(bars, tier_sentiment['sentiment_score']):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
             round(val, 3), ha='center', fontweight='bold')

plt.title('Average Sentiment Score by Player Investment Tier', fontsize=14, fontweight='bold')
plt.xlabel('Player Tier')
plt.ylabel('Average Sentiment Score')
plt.legend()
plt.tight_layout()
plt.savefig('/content/chart2_sentiment_by_tier.png', dpi=150)
plt.show()
print("Chart saved")

# Get all negative reviews
negative_reviews = df[df['voted_up'] == 0]['review'].dropna()

# Clean and tokenize
stop_words = set(stopwords.words('english'))
custom_stopwords = {'game', 'gta', 'rockstar', 'play', 'get', 'one',
                    'like', 'also', 'would', 'still', 'even', 'good',
                    'great', 'really', 'much', 'go', 'got', 'make',
                    'time', 'want', 'know', 'way', 'thing', 'nan'}
stop_words.update(custom_stopwords)

all_words = []
for review in negative_reviews:
    tokens = word_tokenize(str(review).lower())
    words = [w for w in tokens if w.isalpha() and w not in stop_words and len(w) > 2]
    all_words.extend(words)

# Count top words
word_freq = Counter(all_words)
top_words = word_freq.most_common(20)

# Plot
words, counts = zip(*top_words)
plt.figure(figsize=(12, 6))
bars = plt.barh(words[::-1], counts[::-1], color='crimson', edgecolor='white')
plt.title('Top 20 Words in Negative Reviews — What Players Are Complaining About',
          fontsize=13, fontweight='bold')
plt.xlabel('Frequency')
plt.tight_layout()
plt.savefig('/content/chart3_negative_words.png', dpi=150)
plt.show()
print("Top 10 complaint words:")
for word, count in top_words[:10]:
    print(f"  {word}: {count}")

!pip install wordcloud --quiet
from wordcloud import WordCloud

# Build word frequency dictionary
word_dict = dict(word_freq.most_common(100))

# Generate word cloud
wordcloud = WordCloud(
    width=1200, height=600,
    background_color='black',
    colormap='Reds',
    max_words=100,
    collocations=False
).generate_from_frequencies(word_dict)

plt.figure(figsize=(14, 7))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud — Negative Reviews', fontsize=16, fontweight='bold', color='white',
          pad=20)
plt.tight_layout()
plt.savefig('/content/chart4_negative_wordcloud.png', dpi=150,
            bbox_inches='tight', facecolor='black')
plt.show()
print("Word cloud saved")

# Get positive reviews
positive_reviews = df[df['voted_up'] == 1]['review'].dropna()

pos_words = []
for review in positive_reviews:
    tokens = word_tokenize(str(review).lower())
    words = [w for w in tokens if w.isalpha() and w not in stop_words and len(w) > 2]
    pos_words.extend(words)

pos_word_freq = Counter(pos_words)
pos_word_dict = dict(pos_word_freq.most_common(100))

wordcloud_pos = WordCloud(
    width=1200, height=600,
    background_color='black',
    colormap='Blues',
    max_words=100,
    collocations=False
).generate_from_frequencies(pos_word_dict)

plt.figure(figsize=(14, 7))
plt.imshow(wordcloud_pos, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud — Positive Reviews', fontsize=16,
          fontweight='bold', color='white', pad=20)
plt.tight_layout()
plt.savefig('/content/chart5_positive_wordcloud.png', dpi=150,
            bbox_inches='tight', facecolor='black')
plt.show()
print("Positive word cloud saved")

# Select numeric columns for correlation
corr_cols = ['voted_up', 'sentiment_score', 'votes_up', 'comment_count',
             'steam_purchase', 'recieved_for_free', 'written_during_early_access',
             'author_num_games_owned', 'author_num_reviews',
             'playtime_forever_hrs', 'playtime_at_review_hrs',
             'playtime_last_2weeks_hrs']

corr_matrix = df[corr_cols].corr()

plt.figure(figsize=(12, 10))
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='RdYlGn',
            center=0, square=True, linewidths=0.5,
            annot_kws={'size': 9})
plt.title('Correlation Heatmap — What Drives Sentiment',
          fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('/content/chart6_correlation_heatmap.png', dpi=150)
plt.show()
print("Heatmap saved")

churn_data = df[df['voted_up'] == 0].copy()
churn_data['status'] = churn_data['playtime_last_2weeks_hrs'].apply(
    lambda x: 'Frustrated\n(Still Playing)' if x > 0 else 'Churned\n(No Recent Activity)'
)

status_counts = churn_data['status'].value_counts()
colors = ['#2196F3', '#F44336']

plt.figure(figsize=(8, 6))
bars = plt.bar(status_counts.index, status_counts.values,
               color=colors, edgecolor='white', width=0.4)

for bar, val in zip(bars, status_counts.values):
    pct = round(val * 100 / len(churn_data), 1)
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 20,
             f'{val:,}\n({pct}%)', ha='center', fontweight='bold', fontsize=11)

plt.title('Negative Reviewers — Churned vs Still Playing',
          fontsize=14, fontweight='bold')
plt.ylabel('Number of Players')
plt.ylim(0, max(status_counts.values) * 1.2)
plt.tight_layout()
plt.savefig('/content/chart7_churn_vs_frustration.png', dpi=150)
plt.show()
print("Churn chart saved")

# Build composite risk score
df['amplification_risk'] = (
    df['votes_up'] * 2 +
    df['comment_count'] * 1.5 +
    (df['playtime_forever_hrs'] / df['playtime_forever_hrs'].max()) * 10 +
    df['author_num_reviews'].apply(lambda x: 5 if x >= 6 else 0)
)

# Top 15 highest risk negative reviews
top_risk = df[df['voted_up'] == 0].nlargest(15, 'amplification_risk')[
    ['id', 'review', 'votes_up', 'comment_count',
     'playtime_forever_hrs', 'amplification_risk']
].copy()

top_risk['review_preview'] = top_risk['review'].str[:80]

print("Top 10 Highest Risk Negative Reviews:")
print(top_risk[['review_preview', 'votes_up', 'playtime_forever_hrs',
                'amplification_risk']].head(10).to_string())

# Chart
plt.figure(figsize=(12, 6))
plt.barh(range(15), top_risk['amplification_risk'].values[::-1],
         color='darkred', edgecolor='white')
plt.yticks(range(15), top_risk['review_preview'].values[::-1], fontsize=8)
plt.title('Top 15 Highest Risk Negative Reviews by Amplification Score',
          fontsize=13, fontweight='bold')
plt.xlabel('Amplification Risk Score')
plt.tight_layout()
plt.savefig('/content/chart8_amplification_risk.png', dpi=150)
plt.show()
print("Risk chart saved")

def reviewer_type(n):
    if n == 1:
        return 'First Time\nReviewer'
    elif n <= 5:
        return 'Occasional\nReviewer'
    else:
        return 'Habitual\nReviewer (6+)'

df['reviewer_type'] = df['author_num_reviews'].apply(reviewer_type)

rev_sentiment = df.groupby('reviewer_type').agg(
    avg_sentiment=('sentiment_score', 'mean'),
    positive_rate=('voted_up', 'mean'),
    total=('id', 'count')
).reset_index()

fig, ax1 = plt.subplots(figsize=(10, 6))
bars = ax1.bar(rev_sentiment['reviewer_type'],
               rev_sentiment['avg_sentiment'],
               color=['#4CAF50', '#FF9800', '#F44336'],
               edgecolor='white', width=0.4)

ax1.axhline(y=df['sentiment_score'].mean(), color='black',
            linestyle='--', linewidth=1.5,
            label=f'Overall Mean: {round(df["sentiment_score"].mean(), 3)}')

for bar, val in zip(bars, rev_sentiment['avg_sentiment']):
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.003,
             round(val, 3), ha='center', fontweight='bold')

ax1.set_title('Sentiment Score by Reviewer Type', fontsize=14, fontweight='bold')
ax1.set_ylabel('Average Sentiment Score')
ax1.legend()
plt.tight_layout()
plt.savefig('/content/chart9_reviewer_type_sentiment.png', dpi=150)
plt.show()
print("Reviewer type chart saved")

df['month'] = df['created'].dt.to_period('M')
monthly = df.groupby('month').agg(
    avg_sentiment=('sentiment_score', 'mean'),
    positive_rate=('voted_up', 'mean'),
    total=('id', 'count')
).reset_index()

monthly['month_str'] = monthly['month'].astype(str)
monthly = monthly.head(20)

fig, ax1 = plt.subplots(figsize=(14, 6))

color1 = '#1976D2'
ax1.plot(monthly['month_str'], monthly['avg_sentiment'],
         color=color1, linewidth=2.5, marker='o', markersize=5, label='Avg Sentiment Score')
ax1.set_ylabel('Average Sentiment Score', color=color1)
ax1.tick_params(axis='y', labelcolor=color1)
ax1.axhline(y=monthly['avg_sentiment'].mean(), color=color1,
            linestyle='--', alpha=0.5)

ax2 = ax1.twinx()
color2 = '#E53935'
ax2.plot(monthly['month_str'], monthly['positive_rate'] * 100,
         color=color2, linewidth=2.5, marker='s', markersize=5,
         linestyle='--', label='Positive Rate %')
ax2.set_ylabel('Positive Rate (%)', color=color2)
ax2.tick_params(axis='y', labelcolor=color2)

plt.title('Sentiment Trend Over Time — First 20 Months',
          fontsize=14, fontweight='bold')
plt.xticks(rotation=45, ha='right')
fig.legend(loc='upper right', bbox_to_anchor=(0.88, 0.88))
plt.tight_layout()
plt.savefig('/content/chart10_sentiment_trend.png', dpi=150)
plt.show()
print("Trend chart saved")

# Add player segment column
def get_segment(row):
    if row['steam_purchase'] == 1 and row['recieved_for_free'] == 0:
        return 'Paid Player'
    elif row['recieved_for_free'] == 1:
        return 'Free Player'
    else:
        return 'Other'

df['player_segment'] = df.apply(get_segment, axis=1)

# Add churn status
df['churn_status'] = df.apply(
    lambda row: 'Churned' if row['voted_up'] == 0 and row['playtime_last_2weeks_hrs'] == 0
    else ('Frustrated' if row['voted_up'] == 0 and row['playtime_last_2weeks_hrs'] > 0
    else 'Active'), axis=1
)

# Save final enriched dataset
df.to_csv('/content/GTA_FINAL_ENRICHED.csv', index=False)
print("Final dataset saved with", len(df), "rows and", len(df.columns), "columns")
print("New columns added:", ['sentiment_score', 'playtime_forever_hrs',
                              'playtime_at_review_hrs', 'playtime_last_2weeks_hrs',
                              'player_tier', 'reviewer_type',
                              'amplification_risk', 'player_segment', 'churn_status'])

# Download
from google.colab import files
files.download('/content/GTA_FINAL_ENRICHED.csv')
print("Download started")